
install.packages("renv")
renv::install("shiny")
renv::install("bioc::SummarizedExperiment")
renv::install("bioc::ComplexHeatmap")
renv::install("tidyverse")
renv::install("testthat")
renv::install("shinyjs")
renv::install("shinyalert")
renv::install("svglite")
renv::install("bioc::Rhtslib")
renv::install("bioc::Rsamtools")
renv::install("bioc::ensembldb")
renv::install("bioc::EnsDb.Hsapiens.v86")
renv::install("bioc::EnsDb.Mmusculus.v79")
renv::install("plotly")
renv::install("shinyWidgets")
renv::install("ggVennDiagram")
renv::install("rhandsontable")
renv::install("shinyBS")
renv::install("shinycssloaders")
renv::install("shiny.info")
renv::install("fastcluster")
renv::install("factoextra")
renv::install("UpSetR")
renv::install("vegan")
renv::install("assertthat")
renv::install("shinydashboard")
renv::install("bioc::limma")
renv::install("bioc::MSnbase")
renv::install("bioc::cmapR")
renv::install("bioc::ConsensusClusterPlus")
renv::install("Nesvilab/FragPipeAnalystR")
renv::install("nicolerg/ssGSEA2")


